/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.100
 * Generated at: 2024-06-07 02:08:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.star_002dadmin2_002dfree_002dadmin_002dtemplate.template.pages.tables;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class basic_002dtable_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/Users/nguyenvanhau/NetBeansProjects/BtlTrangSucJdk15ss/build/web/WEB-INF/lib/jstl-impl.jar!/META-INF/c.tld", Long.valueOf(1343794618000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-impl.jar", Long.valueOf(1716547728012L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("  <!-- Required meta tags -->\n");
      out.write("  <meta charset=\"utf-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("  <title>Star Admin2 </title>\n");
      out.write("  <!-- plugins:css -->\n");
      out.write("  <link rel=\"stylesheet\" href=\"../../vendors/feather/feather.css\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"../../vendors/mdi/css/materialdesignicons.min.css\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"../../vendors/ti-icons/css/themify-icons.css\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"../../vendors/typicons/typicons.css\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"../../vendors/simple-line-icons/css/simple-line-icons.css\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"../../vendors/css/vendor.bundle.base.css\">\n");
      out.write("  <!-- endinject -->\n");
      out.write("  <!-- Plugin css for this page -->\n");
      out.write("  <!-- End plugin css for this page -->\n");
      out.write("  <!-- inject:css -->\n");
      out.write("  <link rel=\"stylesheet\" href=\"../../css/vertical-layout-light/style.css\">\n");
      out.write("  <!-- endinject -->\n");
      out.write("  <link rel=\"shortcut icon\" href=\"../../images/favicon.png\" />\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("  <div class=\"container-scroller\">\n");
      out.write("    <!-- partial:../../partials/_navbar.html -->\n");
      out.write("    <nav class=\"navbar default-layout col-lg-12 col-12 p-0 fixed-top d-flex align-items-top flex-row\">\n");
      out.write("      <div class=\"text-center navbar-brand-wrapper d-flex align-items-center justify-content-start\">\n");
      out.write("        <div class=\"me-3\">\n");
      out.write("          <button class=\"navbar-toggler navbar-toggler align-self-center\" type=\"button\" data-bs-toggle=\"minimize\">\n");
      out.write("            <span class=\"icon-menu\"></span>\n");
      out.write("          </button>\n");
      out.write("        </div>\n");
      out.write("        <div>\n");
      out.write("          <a class=\"navbar-brand brand-logo\" href=\"../../index.html\">\n");
      out.write("            <img src=\"../../images/logo.svg\" alt=\"logo\" />\n");
      out.write("          </a>\n");
      out.write("          <a class=\"navbar-brand brand-logo-mini\" href=\"../../index.html\">\n");
      out.write("            <img src=\"../../images/logo-mini.svg\" alt=\"logo\" />\n");
      out.write("          </a>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"navbar-menu-wrapper d-flex align-items-top\"> \n");
      out.write("        <ul class=\"navbar-nav\">\n");
      out.write("          <li class=\"nav-item font-weight-semibold d-none d-lg-block ms-0\">\n");
      out.write("            <h1 class=\"welcome-text\">Good Morning, <span class=\"text-black fw-bold\">John Doe</span></h1>\n");
      out.write("            <h3 class=\"welcome-sub-text\">Your performance summary this week </h3>\n");
      out.write("          </li>\n");
      out.write("        </ul>\n");
      out.write("        <ul class=\"navbar-nav ms-auto\">\n");
      out.write("          <li class=\"nav-item dropdown d-none d-lg-block\">\n");
      out.write("            <a class=\"nav-link dropdown-bordered dropdown-toggle dropdown-toggle-split\" id=\"messageDropdown\" href=\"#\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\"> Select Category </a>\n");
      out.write("            <div class=\"dropdown-menu dropdown-menu-right navbar-dropdown preview-list pb-0\" aria-labelledby=\"messageDropdown\">\n");
      out.write("              <a class=\"dropdown-item py-3\" >\n");
      out.write("                <p class=\"mb-0 font-weight-medium float-left\">Select category</p>\n");
      out.write("              </a>\n");
      out.write("              <div class=\"dropdown-divider\"></div>\n");
      out.write("              <a class=\"dropdown-item preview-item\">\n");
      out.write("                <div class=\"preview-item-content flex-grow py-2\">\n");
      out.write("                  <p class=\"preview-subject ellipsis font-weight-medium text-dark\">Bootstrap Bundle </p>\n");
      out.write("                  <p class=\"fw-light small-text mb-0\">This is a Bundle featuring 16 unique dashboards</p>\n");
      out.write("                </div>\n");
      out.write("              </a>\n");
      out.write("              <a class=\"dropdown-item preview-item\">\n");
      out.write("                <div class=\"preview-item-content flex-grow py-2\">\n");
      out.write("                  <p class=\"preview-subject ellipsis font-weight-medium text-dark\">Angular Bundle</p>\n");
      out.write("                  <p class=\"fw-light small-text mb-0\">Everything you’ll ever need for your Angular projects</p>\n");
      out.write("                </div>\n");
      out.write("              </a>\n");
      out.write("              <a class=\"dropdown-item preview-item\">\n");
      out.write("                <div class=\"preview-item-content flex-grow py-2\">\n");
      out.write("                  <p class=\"preview-subject ellipsis font-weight-medium text-dark\">VUE Bundle</p>\n");
      out.write("                  <p class=\"fw-light small-text mb-0\">Bundle of 6 Premium Vue Admin Dashboard</p>\n");
      out.write("                </div>\n");
      out.write("              </a>\n");
      out.write("              <a class=\"dropdown-item preview-item\">\n");
      out.write("                <div class=\"preview-item-content flex-grow py-2\">\n");
      out.write("                  <p class=\"preview-subject ellipsis font-weight-medium text-dark\">React Bundle</p>\n");
      out.write("                  <p class=\"fw-light small-text mb-0\">Bundle of 8 Premium React Admin Dashboard</p>\n");
      out.write("                </div>\n");
      out.write("              </a>\n");
      out.write("            </div>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"nav-item d-none d-lg-block\">\n");
      out.write("            <div id=\"datepicker-popup\" class=\"input-group date datepicker navbar-date-picker\">\n");
      out.write("              <span class=\"input-group-addon input-group-prepend border-right\">\n");
      out.write("                <span class=\"icon-calendar input-group-text calendar-icon\"></span>\n");
      out.write("              </span>\n");
      out.write("              <input type=\"text\" class=\"form-control\">\n");
      out.write("            </div>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"nav-item\">\n");
      out.write("            <form class=\"search-form\" action=\"#\">\n");
      out.write("              <i class=\"icon-search\"></i>\n");
      out.write("              <input type=\"search\" class=\"form-control\" placeholder=\"Search Here\" title=\"Search here\">\n");
      out.write("            </form>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"nav-item dropdown\">\n");
      out.write("            <a class=\"nav-link count-indicator\" id=\"notificationDropdown\" href=\"#\" data-bs-toggle=\"dropdown\">\n");
      out.write("              <i class=\"icon-mail icon-lg\"></i>\n");
      out.write("            </a>\n");
      out.write("            <div class=\"dropdown-menu dropdown-menu-right navbar-dropdown preview-list pb-0\" aria-labelledby=\"notificationDropdown\">\n");
      out.write("              <a class=\"dropdown-item py-3 border-bottom\">\n");
      out.write("                <p class=\"mb-0 font-weight-medium float-left\">You have 4 new notifications </p>\n");
      out.write("                <span class=\"badge badge-pill badge-primary float-right\">View all</span>\n");
      out.write("              </a>\n");
      out.write("              <a class=\"dropdown-item preview-item py-3\">\n");
      out.write("                <div class=\"preview-thumbnail\">\n");
      out.write("                  <i class=\"mdi mdi-alert m-auto text-primary\"></i>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"preview-item-content\">\n");
      out.write("                  <h6 class=\"preview-subject fw-normal text-dark mb-1\">Application Error</h6>\n");
      out.write("                  <p class=\"fw-light small-text mb-0\"> Just now </p>\n");
      out.write("                </div>\n");
      out.write("              </a>\n");
      out.write("              <a class=\"dropdown-item preview-item py-3\">\n");
      out.write("                <div class=\"preview-thumbnail\">\n");
      out.write("                  <i class=\"mdi mdi-settings m-auto text-primary\"></i>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"preview-item-content\">\n");
      out.write("                  <h6 class=\"preview-subject fw-normal text-dark mb-1\">Settings</h6>\n");
      out.write("                  <p class=\"fw-light small-text mb-0\"> Private message </p>\n");
      out.write("                </div>\n");
      out.write("              </a>\n");
      out.write("              <a class=\"dropdown-item preview-item py-3\">\n");
      out.write("                <div class=\"preview-thumbnail\">\n");
      out.write("                  <i class=\"mdi mdi-airballoon m-auto text-primary\"></i>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"preview-item-content\">\n");
      out.write("                  <h6 class=\"preview-subject fw-normal text-dark mb-1\">New user registration</h6>\n");
      out.write("                  <p class=\"fw-light small-text mb-0\"> 2 days ago </p>\n");
      out.write("                </div>\n");
      out.write("              </a>\n");
      out.write("            </div>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"nav-item dropdown\"> \n");
      out.write("            <a class=\"nav-link count-indicator\" id=\"countDropdown\" href=\"#\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\n");
      out.write("              <i class=\"icon-bell\"></i>\n");
      out.write("              <span class=\"count\"></span>\n");
      out.write("            </a>\n");
      out.write("            <div class=\"dropdown-menu dropdown-menu-right navbar-dropdown preview-list pb-0\" aria-labelledby=\"countDropdown\">\n");
      out.write("              <a class=\"dropdown-item py-3\">\n");
      out.write("                <p class=\"mb-0 font-weight-medium float-left\">You have 7 unread mails </p>\n");
      out.write("                <span class=\"badge badge-pill badge-primary float-right\">View all</span>\n");
      out.write("              </a>\n");
      out.write("              <div class=\"dropdown-divider\"></div>\n");
      out.write("              <a class=\"dropdown-item preview-item\">\n");
      out.write("                <div class=\"preview-thumbnail\">\n");
      out.write("                  <img src=\"../../images/faces/face10.jpg\" alt=\"image\" class=\"img-sm profile-pic\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"preview-item-content flex-grow py-2\">\n");
      out.write("                  <p class=\"preview-subject ellipsis font-weight-medium text-dark\">Marian Garner </p>\n");
      out.write("                  <p class=\"fw-light small-text mb-0\"> The meeting is cancelled </p>\n");
      out.write("                </div>\n");
      out.write("              </a>\n");
      out.write("              <a class=\"dropdown-item preview-item\">\n");
      out.write("                <div class=\"preview-thumbnail\">\n");
      out.write("                  <img src=\"../../images/faces/face12.jpg\" alt=\"image\" class=\"img-sm profile-pic\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"preview-item-content flex-grow py-2\">\n");
      out.write("                  <p class=\"preview-subject ellipsis font-weight-medium text-dark\">David Grey </p>\n");
      out.write("                  <p class=\"fw-light small-text mb-0\"> The meeting is cancelled </p>\n");
      out.write("                </div>\n");
      out.write("              </a>\n");
      out.write("              <a class=\"dropdown-item preview-item\">\n");
      out.write("                <div class=\"preview-thumbnail\">\n");
      out.write("                  <img src=\"../../images/faces/face1.jpg\" alt=\"image\" class=\"img-sm profile-pic\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"preview-item-content flex-grow py-2\">\n");
      out.write("                  <p class=\"preview-subject ellipsis font-weight-medium text-dark\">Travis Jenkins </p>\n");
      out.write("                  <p class=\"fw-light small-text mb-0\"> The meeting is cancelled </p>\n");
      out.write("                </div>\n");
      out.write("              </a>\n");
      out.write("            </div>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"nav-item dropdown d-none d-lg-block user-dropdown\">\n");
      out.write("            <a class=\"nav-link\" id=\"UserDropdown\" href=\"#\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\n");
      out.write("              <img class=\"img-xs rounded-circle\" src=\"../../images/faces/face8.jpg\" alt=\"Profile image\"> </a>\n");
      out.write("            <div class=\"dropdown-menu dropdown-menu-right navbar-dropdown\" aria-labelledby=\"UserDropdown\">\n");
      out.write("              <div class=\"dropdown-header text-center\">\n");
      out.write("                <img class=\"img-md rounded-circle\" src=\"../../images/faces/face8.jpg\" alt=\"Profile image\">\n");
      out.write("                <p class=\"mb-1 mt-3 font-weight-semibold\">Allen Moreno</p>\n");
      out.write("                <p class=\"fw-light text-muted mb-0\">allenmoreno@gmail.com</p>\n");
      out.write("              </div>\n");
      out.write("              <a class=\"dropdown-item\"><i class=\"dropdown-item-icon mdi mdi-account-outline text-primary me-2\"></i> My Profile <span class=\"badge badge-pill badge-danger\">1</span></a>\n");
      out.write("              <a class=\"dropdown-item\"><i class=\"dropdown-item-icon mdi mdi-message-text-outline text-primary me-2\"></i> Messages</a>\n");
      out.write("              <a class=\"dropdown-item\"><i class=\"dropdown-item-icon mdi mdi-calendar-check-outline text-primary me-2\"></i> Activity</a>\n");
      out.write("              <a class=\"dropdown-item\"><i class=\"dropdown-item-icon mdi mdi-help-circle-outline text-primary me-2\"></i> FAQ</a>\n");
      out.write("              <a class=\"dropdown-item\"><i class=\"dropdown-item-icon mdi mdi-power text-primary me-2\"></i>Sign Out</a>\n");
      out.write("            </div>\n");
      out.write("          </li>\n");
      out.write("        </ul>\n");
      out.write("        <button class=\"navbar-toggler navbar-toggler-right d-lg-none align-self-center\" type=\"button\" data-bs-toggle=\"offcanvas\">\n");
      out.write("          <span class=\"mdi mdi-menu\"></span>\n");
      out.write("        </button>\n");
      out.write("      </div>\n");
      out.write("    </nav>\n");
      out.write("    <!-- partial -->\n");
      out.write("    <div class=\"container-fluid page-body-wrapper\">\n");
      out.write("      <!-- partial:../../partials/_settings-panel.html -->\n");
      out.write("      <div class=\"theme-setting-wrapper\">\n");
      out.write("        <div id=\"settings-trigger\"><i class=\"ti-settings\"></i></div>\n");
      out.write("        <div id=\"theme-settings\" class=\"settings-panel\">\n");
      out.write("          <i class=\"settings-close ti-close\"></i>\n");
      out.write("          <p class=\"settings-heading\">SIDEBAR SKINS</p>\n");
      out.write("          <div class=\"sidebar-bg-options selected\" id=\"sidebar-light-theme\"><div class=\"img-ss rounded-circle bg-light border me-3\"></div>Light</div>\n");
      out.write("          <div class=\"sidebar-bg-options\" id=\"sidebar-dark-theme\"><div class=\"img-ss rounded-circle bg-dark border me-3\"></div>Dark</div>\n");
      out.write("          <p class=\"settings-heading mt-2\">HEADER SKINS</p>\n");
      out.write("          <div class=\"color-tiles mx-0 px-4\">\n");
      out.write("            <div class=\"tiles success\"></div>\n");
      out.write("            <div class=\"tiles warning\"></div>\n");
      out.write("            <div class=\"tiles danger\"></div>\n");
      out.write("            <div class=\"tiles info\"></div>\n");
      out.write("            <div class=\"tiles dark\"></div>\n");
      out.write("            <div class=\"tiles default\"></div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div id=\"right-sidebar\" class=\"settings-panel\">\n");
      out.write("        <i class=\"settings-close ti-close\"></i>\n");
      out.write("        <ul class=\"nav nav-tabs border-top\" id=\"setting-panel\" role=\"tablist\">\n");
      out.write("          <li class=\"nav-item\">\n");
      out.write("            <a class=\"nav-link active\" id=\"todo-tab\" data-bs-toggle=\"tab\" href=\"#todo-section\" role=\"tab\" aria-controls=\"todo-section\" aria-expanded=\"true\">TO DO LIST</a>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"nav-item\">\n");
      out.write("            <a class=\"nav-link\" id=\"chats-tab\" data-bs-toggle=\"tab\" href=\"#chats-section\" role=\"tab\" aria-controls=\"chats-section\">CHATS</a>\n");
      out.write("          </li>\n");
      out.write("        </ul>\n");
      out.write("        <div class=\"tab-content\" id=\"setting-content\">\n");
      out.write("          <div class=\"tab-pane fade show active scroll-wrapper\" id=\"todo-section\" role=\"tabpanel\" aria-labelledby=\"todo-section\">\n");
      out.write("            <div class=\"add-items d-flex px-3 mb-0\">\n");
      out.write("              <form class=\"form w-100\">\n");
      out.write("                <div class=\"form-group d-flex\">\n");
      out.write("                  <input type=\"text\" class=\"form-control todo-list-input\" placeholder=\"Add To-do\">\n");
      out.write("                  <button type=\"submit\" class=\"add btn btn-primary todo-list-add-btn\" id=\"add-task\">Add</button>\n");
      out.write("                </div>\n");
      out.write("              </form>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"list-wrapper px-3\">\n");
      out.write("              <ul class=\"d-flex flex-column-reverse todo-list\">\n");
      out.write("                <li>\n");
      out.write("                  <div class=\"form-check\">\n");
      out.write("                    <label class=\"form-check-label\">\n");
      out.write("                      <input class=\"checkbox\" type=\"checkbox\">\n");
      out.write("                      Team review meeting at 3.00 PM\n");
      out.write("                    </label>\n");
      out.write("                  </div>\n");
      out.write("                  <i class=\"remove ti-close\"></i>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                  <div class=\"form-check\">\n");
      out.write("                    <label class=\"form-check-label\">\n");
      out.write("                      <input class=\"checkbox\" type=\"checkbox\">\n");
      out.write("                      Prepare for presentation\n");
      out.write("                    </label>\n");
      out.write("                  </div>\n");
      out.write("                  <i class=\"remove ti-close\"></i>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                  <div class=\"form-check\">\n");
      out.write("                    <label class=\"form-check-label\">\n");
      out.write("                      <input class=\"checkbox\" type=\"checkbox\">\n");
      out.write("                      Resolve all the low priority tickets due today\n");
      out.write("                    </label>\n");
      out.write("                  </div>\n");
      out.write("                  <i class=\"remove ti-close\"></i>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"completed\">\n");
      out.write("                  <div class=\"form-check\">\n");
      out.write("                    <label class=\"form-check-label\">\n");
      out.write("                      <input class=\"checkbox\" type=\"checkbox\" checked>\n");
      out.write("                      Schedule meeting for next week\n");
      out.write("                    </label>\n");
      out.write("                  </div>\n");
      out.write("                  <i class=\"remove ti-close\"></i>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"completed\">\n");
      out.write("                  <div class=\"form-check\">\n");
      out.write("                    <label class=\"form-check-label\">\n");
      out.write("                      <input class=\"checkbox\" type=\"checkbox\" checked>\n");
      out.write("                      Project review\n");
      out.write("                    </label>\n");
      out.write("                  </div>\n");
      out.write("                  <i class=\"remove ti-close\"></i>\n");
      out.write("                </li>\n");
      out.write("              </ul>\n");
      out.write("            </div>\n");
      out.write("            <h4 class=\"px-3 text-muted mt-5 fw-light mb-0\">Events</h4>\n");
      out.write("            <div class=\"events pt-4 px-3\">\n");
      out.write("              <div class=\"wrapper d-flex mb-2\">\n");
      out.write("                <i class=\"ti-control-record text-primary me-2\"></i>\n");
      out.write("                <span>Feb 11 2018</span>\n");
      out.write("              </div>\n");
      out.write("              <p class=\"mb-0 font-weight-thin text-gray\">Creating component page build a js</p>\n");
      out.write("              <p class=\"text-gray mb-0\">The total number of sessions</p>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"events pt-4 px-3\">\n");
      out.write("              <div class=\"wrapper d-flex mb-2\">\n");
      out.write("                <i class=\"ti-control-record text-primary me-2\"></i>\n");
      out.write("                <span>Feb 7 2018</span>\n");
      out.write("              </div>\n");
      out.write("              <p class=\"mb-0 font-weight-thin text-gray\">Meeting with Alisa</p>\n");
      out.write("              <p class=\"text-gray mb-0 \">Call Sarah Graves</p>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <!-- To do section tab ends -->\n");
      out.write("          <div class=\"tab-pane fade\" id=\"chats-section\" role=\"tabpanel\" aria-labelledby=\"chats-section\">\n");
      out.write("            <div class=\"d-flex align-items-center justify-content-between border-bottom\">\n");
      out.write("              <p class=\"settings-heading border-top-0 mb-3 pl-3 pt-0 border-bottom-0 pb-0\">Friends</p>\n");
      out.write("              <small class=\"settings-heading border-top-0 mb-3 pt-0 border-bottom-0 pb-0 pr-3 fw-normal\">See All</small>\n");
      out.write("            </div>\n");
      out.write("            <ul class=\"chat-list\">\n");
      out.write("              <li class=\"list active\">\n");
      out.write("                <div class=\"profile\"><img src=\"../../images/faces/face1.jpg\" alt=\"image\"><span class=\"online\"></span></div>\n");
      out.write("                <div class=\"info\">\n");
      out.write("                  <p>Thomas Douglas</p>\n");
      out.write("                  <p>Available</p>\n");
      out.write("                </div>\n");
      out.write("                <small class=\"text-muted my-auto\">19 min</small>\n");
      out.write("              </li>\n");
      out.write("              <li class=\"list\">\n");
      out.write("                <div class=\"profile\"><img src=\"../../images/faces/face2.jpg\" alt=\"image\"><span class=\"offline\"></span></div>\n");
      out.write("                <div class=\"info\">\n");
      out.write("                  <div class=\"wrapper d-flex\">\n");
      out.write("                    <p>Catherine</p>\n");
      out.write("                  </div>\n");
      out.write("                  <p>Away</p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"badge badge-success badge-pill my-auto mx-2\">4</div>\n");
      out.write("                <small class=\"text-muted my-auto\">23 min</small>\n");
      out.write("              </li>\n");
      out.write("              <li class=\"list\">\n");
      out.write("                <div class=\"profile\"><img src=\"../../images/faces/face3.jpg\" alt=\"image\"><span class=\"online\"></span></div>\n");
      out.write("                <div class=\"info\">\n");
      out.write("                  <p>Daniel Russell</p>\n");
      out.write("                  <p>Available</p>\n");
      out.write("                </div>\n");
      out.write("                <small class=\"text-muted my-auto\">14 min</small>\n");
      out.write("              </li>\n");
      out.write("              <li class=\"list\">\n");
      out.write("                <div class=\"profile\"><img src=\"../../images/faces/face4.jpg\" alt=\"image\"><span class=\"offline\"></span></div>\n");
      out.write("                <div class=\"info\">\n");
      out.write("                  <p>James Richardson</p>\n");
      out.write("                  <p>Away</p>\n");
      out.write("                </div>\n");
      out.write("                <small class=\"text-muted my-auto\">2 min</small>\n");
      out.write("              </li>\n");
      out.write("              <li class=\"list\">\n");
      out.write("                <div class=\"profile\"><img src=\"../../images/faces/face5.jpg\" alt=\"image\"><span class=\"online\"></span></div>\n");
      out.write("                <div class=\"info\">\n");
      out.write("                  <p>Madeline Kennedy</p>\n");
      out.write("                  <p>Available</p>\n");
      out.write("                </div>\n");
      out.write("                <small class=\"text-muted my-auto\">5 min</small>\n");
      out.write("              </li>\n");
      out.write("              <li class=\"list\">\n");
      out.write("                <div class=\"profile\"><img src=\"../../images/faces/face6.jpg\" alt=\"image\"><span class=\"online\"></span></div>\n");
      out.write("                <div class=\"info\">\n");
      out.write("                  <p>Sarah Graves</p>\n");
      out.write("                  <p>Available</p>\n");
      out.write("                </div>\n");
      out.write("                <small class=\"text-muted my-auto\">47 min</small>\n");
      out.write("              </li>\n");
      out.write("            </ul>\n");
      out.write("          </div>\n");
      out.write("          <!-- chat tab ends -->\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <!-- partial -->\n");
      out.write("      <!-- partial:../../partials/_sidebar.html -->\n");
      out.write("      <nav class=\"sidebar sidebar-offcanvas\" id=\"sidebar\">\n");
      out.write("        <ul class=\"nav\">\n");
      out.write("          <li class=\"nav-item\">\n");
      out.write("            <a class=\"nav-link\" href=\"../../index.html\">\n");
      out.write("              <i class=\"mdi mdi-grid-large menu-icon\"></i>\n");
      out.write("              <span class=\"menu-title\">Dashboard</span>\n");
      out.write("            </a>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"nav-item nav-category\">UI Elements</li>\n");
      out.write("          <li class=\"nav-item\">\n");
      out.write("            <a class=\"nav-link\" data-bs-toggle=\"collapse\" href=\"#ui-basic\" aria-expanded=\"false\" aria-controls=\"ui-basic\">\n");
      out.write("              <i class=\"menu-icon mdi mdi-floor-plan\"></i>\n");
      out.write("              <span class=\"menu-title\">UI Elements</span>\n");
      out.write("              <i class=\"menu-arrow\"></i> \n");
      out.write("            </a>\n");
      out.write("            <div class=\"collapse\" id=\"ui-basic\">\n");
      out.write("              <ul class=\"nav flex-column sub-menu\">\n");
      out.write("                <li class=\"nav-item\"> <a class=\"nav-link\" href=\"../../pages/ui-features/buttons.html\">Buttons</a></li>\n");
      out.write("                <li class=\"nav-item\"> <a class=\"nav-link\" href=\"../../pages/ui-features/dropdowns.html\">Dropdowns</a></li>\n");
      out.write("                <li class=\"nav-item\"> <a class=\"nav-link\" href=\"../../pages/ui-features/typography.html\">Typography</a></li>\n");
      out.write("              </ul>\n");
      out.write("            </div>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"nav-item nav-category\">Forms and Datas</li>\n");
      out.write("          <li class=\"nav-item\">\n");
      out.write("            <a class=\"nav-link\" data-bs-toggle=\"collapse\" href=\"#form-elements\" aria-expanded=\"false\" aria-controls=\"form-elements\">\n");
      out.write("              <i class=\"menu-icon mdi mdi-card-text-outline\"></i>\n");
      out.write("              <span class=\"menu-title\">Form elements</span>\n");
      out.write("              <i class=\"menu-arrow\"></i>\n");
      out.write("            </a>\n");
      out.write("            <div class=\"collapse\" id=\"form-elements\">\n");
      out.write("              <ul class=\"nav flex-column sub-menu\">\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"../../pages/forms/basic_elements.html\">Basic Elements</a></li>\n");
      out.write("              </ul>\n");
      out.write("            </div>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"nav-item\">\n");
      out.write("            <a class=\"nav-link\" data-bs-toggle=\"collapse\" href=\"#charts\" aria-expanded=\"false\" aria-controls=\"charts\">\n");
      out.write("              <i class=\"menu-icon mdi mdi-chart-line\"></i>\n");
      out.write("              <span class=\"menu-title\">Charts</span>\n");
      out.write("              <i class=\"menu-arrow\"></i>\n");
      out.write("            </a>\n");
      out.write("            <div class=\"collapse\" id=\"charts\">\n");
      out.write("              <ul class=\"nav flex-column sub-menu\">\n");
      out.write("                <li class=\"nav-item\"> <a class=\"nav-link\" href=\"../../pages/charts/chartjs.html\">ChartJs</a></li>\n");
      out.write("              </ul>\n");
      out.write("            </div>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"nav-item\">\n");
      out.write("            <a class=\"nav-link\" data-bs-toggle=\"collapse\" href=\"#tables\" aria-expanded=\"false\" aria-controls=\"tables\">\n");
      out.write("              <i class=\"menu-icon mdi mdi-table\"></i>\n");
      out.write("              <span class=\"menu-title\">Tables</span>\n");
      out.write("              <i class=\"menu-arrow\"></i>\n");
      out.write("            </a>\n");
      out.write("            <div class=\"collapse\" id=\"tables\">\n");
      out.write("              <ul class=\"nav flex-column sub-menu\">\n");
      out.write("                <li class=\"nav-item\"> <a class=\"nav-link\" href=\"../../pages/tables/basic-table.html\">Basic table</a></li>\n");
      out.write("              </ul>\n");
      out.write("            </div>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"nav-item\">\n");
      out.write("            <a class=\"nav-link\" data-bs-toggle=\"collapse\" href=\"#icons\" aria-expanded=\"false\" aria-controls=\"icons\">\n");
      out.write("              <i class=\"menu-icon mdi mdi-layers-outline\"></i>\n");
      out.write("              <span class=\"menu-title\">Icons</span>\n");
      out.write("              <i class=\"menu-arrow\"></i>\n");
      out.write("            </a>\n");
      out.write("            <div class=\"collapse\" id=\"icons\">\n");
      out.write("              <ul class=\"nav flex-column sub-menu\">\n");
      out.write("                <li class=\"nav-item\"> <a class=\"nav-link\" href=\"../../pages/icons/mdi.html\">Mdi icons</a></li>\n");
      out.write("              </ul>\n");
      out.write("            </div>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"nav-item nav-category\">pages</li>\n");
      out.write("          <li class=\"nav-item\">\n");
      out.write("            <a class=\"nav-link\" data-bs-toggle=\"collapse\" href=\"#auth\" aria-expanded=\"false\" aria-controls=\"auth\">\n");
      out.write("              <i class=\"menu-icon mdi mdi-account-circle-outline\"></i>\n");
      out.write("              <span class=\"menu-title\">User Pages</span>\n");
      out.write("              <i class=\"menu-arrow\"></i>\n");
      out.write("            </a>\n");
      out.write("            <div class=\"collapse\" id=\"auth\">\n");
      out.write("              <ul class=\"nav flex-column sub-menu\">\n");
      out.write("                <li class=\"nav-item\"> <a class=\"nav-link\" href=\"../../pages/samples/login.html\"> Login </a></li>\n");
      out.write("              </ul>\n");
      out.write("            </div>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"nav-item nav-category\">help</li>\n");
      out.write("          <li class=\"nav-item\">\n");
      out.write("            <a class=\"nav-link\" href=\"http://bootstrapdash.com/demo/star-admin2-free/docs/documentation.html\">\n");
      out.write("              <i class=\"menu-icon mdi mdi-file-document\"></i>\n");
      out.write("              <span class=\"menu-title\">Documentation</span>\n");
      out.write("            </a>\n");
      out.write("          </li>\n");
      out.write("        </ul>\n");
      out.write("      </nav>\n");
      out.write("      <!-- partial -->\n");
      out.write("      <div class=\"main-panel\">\n");
      out.write("        <div class=\"content-wrapper\">\n");
      out.write("          <div class=\"row\">\n");
      out.write("            <div class=\"col-lg-6 grid-margin stretch-card\">\n");
      out.write("              <div class=\"card\">\n");
      out.write("                <div class=\"card-body\">\n");
      out.write("                  <h4 class=\"card-title\">Basic Table</h4>\n");
      out.write("                  <a href=\"../../../../edits?type=edit\" class=\"card-description\">\n");
      out.write("                    Add class <code>.table</code>\n");
      out.write("                  </a>\n");
      out.write("                  <div class=\"table-responsive\">\n");
      out.write("                    <table class=\"table\">\n");
      out.write("                      <thead>\n");
      out.write("                        <tr>\n");
      out.write("                          <th>id</th>\n");
      out.write("                          <th>Tên loại</th>\n");
      out.write("                          <th>Ngày tạo</th>\n");
      out.write("                          <th>Trạng thái</th>\n");
      out.write("                        </tr>\n");
      out.write("                      </thead>  \n");
      out.write("                      <tbody>\n");
      out.write("                         ");
      com.webtrasua.Controller.CategoryController Daos = null;
      Daos = (com.webtrasua.Controller.CategoryController) _jspx_page_context.getAttribute("Daos", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (Daos == null){
        Daos = new com.webtrasua.Controller.CategoryController();
        _jspx_page_context.setAttribute("Daos", Daos, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write("\n");
      out.write("                          ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                        \n");
      out.write("                        \n");
      out.write("                      </tbody>\n");
      out.write("                    </table>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-lg-6 grid-margin stretch-card\">\n");
      out.write("              <div class=\"card\">\n");
      out.write("                <div class=\"card-body\">\n");
      out.write("                  <h4 class=\"card-title\">Hoverable Table</h4>\n");
      out.write("                  <a href=\"../../../../editPs?type=adds\" class=\"card-description\">\n");
      out.write("                    Add Product\n");
      out.write("                  </a>\n");
      out.write("                  <div class=\"table-responsive\">\n");
      out.write("                    <table class=\"table table-hover\">\n");
      out.write("                      <thead>\n");
      out.write("                          \n");
      out.write("                        <tr>\n");
      out.write("                          <th>id</th>\n");
      out.write("                          <th>title</th>\n");
      out.write("                          <th>name</th>\n");
      out.write("                          <th>price</th>\n");
      out.write("                        </tr>\n");
      out.write("                      </thead>\n");
      out.write("                      <tbody>\n");
      out.write("                          ");
      com.webtrasua.Controller.ProductController PrDao = null;
      PrDao = (com.webtrasua.Controller.ProductController) _jspx_page_context.getAttribute("PrDao", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (PrDao == null){
        PrDao = new com.webtrasua.Controller.ProductController();
        _jspx_page_context.setAttribute("PrDao", PrDao, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write("\n");
      out.write("                          ");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                        \n");
      out.write("                        \n");
      out.write("                      </tbody>\n");
      out.write("                    </table>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-lg-12 grid-margin stretch-card\">\n");
      out.write("              <div class=\"card\">\n");
      out.write("                <div class=\"card-body\">\n");
      out.write("                  <h4 class=\"card-title\">Striped Table</h4>\n");
      out.write("                  <a href=\"../../../../accountAdmin?type=add\" class=\"card-description\">\n");
      out.write("                    Add class <code>.table-striped</code>\n");
      out.write("                  </a>\n");
      out.write("                  <div class=\"table-responsive\">\n");
      out.write("                    <table class=\"table table-striped\">\n");
      out.write("                      <thead>\n");
      out.write("                          <tr>\n");
      out.write("                              <th>Id</th>\n");
      out.write("                              <th>Tên tài khoản</th>\n");
      out.write("                              <th>Mật khẩu</th>\n");
      out.write("                              <th>Quyền bán</th>\n");
      out.write("                              <th>Quyền admin</th>\n");
      out.write("                              <th>Chức năng</th>\n");
      out.write("                          </tr>\n");
      out.write("                      </thead>\n");
      out.write("                      <tbody>\n");
      out.write("                          ");
      com.webtrasua.Controller.AccountController DaoUse = null;
      DaoUse = (com.webtrasua.Controller.AccountController) _jspx_page_context.getAttribute("DaoUse", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (DaoUse == null){
        DaoUse = new com.webtrasua.Controller.AccountController();
        _jspx_page_context.setAttribute("DaoUse", DaoUse, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write("\n");
      out.write("                          ");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                      </tbody>\n");
      out.write("                    </table>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-lg-12 grid-margin stretch-card\">\n");
      out.write("              <div class=\"card\">\n");
      out.write("                <div class=\"card-body\">\n");
      out.write("                  <h4 class=\"card-title\">Thống kê</h4>\n");
      out.write("                  <a href=\"../../../../accountAdmin?type=add\" class=\"card-description\">\n");
      out.write("                    Add class <code>.table-striped</code>\n");
      out.write("                  </a>\n");
      out.write("                  <div class=\"table-responsive\">\n");
      out.write("                    <table class=\"table table-striped\">\n");
      out.write("                      <thead>\n");
      out.write("                          <tr>\n");
      out.write("                              <th>Id</th>\n");
      out.write("                              <th>Tên tài khoản</th>\n");
      out.write("                              <th>Mật khẩu</th>\n");
      out.write("                              <th>Quyền bán</th>\n");
      out.write("                              <th>Quyền admin</th>\n");
      out.write("                              <th>Chức năng</th>\n");
      out.write("                          </tr>\n");
      out.write("                      </thead>\n");
      out.write("                      <tbody>\n");
      out.write("                          ");
      com.webtrasua.Controller.ProductController Totalmoney1 = null;
      Totalmoney1 = (com.webtrasua.Controller.ProductController) _jspx_page_context.getAttribute("Totalmoney1", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (Totalmoney1 == null){
        Totalmoney1 = new com.webtrasua.Controller.ProductController();
        _jspx_page_context.setAttribute("Totalmoney1", Totalmoney1, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write("\n");
      out.write("                          \n");
      out.write("                              ");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                              <tr>\n");
      out.write("                                  <td><h1>Tổng thu nhập: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${soluong}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("VNĐ</h1>\n");
      out.write("                                      <h6 style=\"margin-top: 80px;\">Sản phẩm mua nhiều nhất</h6>\n");
      out.write("                                  </td>\n");
      out.write("                                  \n");
      out.write("                                  \n");
      out.write("                                 \n");
      out.write("                              </tr>\n");
      out.write("                              ");
      if (_jspx_meth_c_005fforEach_005f3(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                      <td><h6>Người dùng mua nhiều nhất</h6></td>\n");
      out.write("                              ");
      if (_jspx_meth_c_005fforEach_005f4(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                              \n");
      out.write("                      </tbody>\n");
      out.write("                    </table>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- content-wrapper ends -->\n");
      out.write("        <!-- partial:../../partials/_footer.html -->\n");
      out.write("        <footer class=\"footer\">\n");
      out.write("          <div class=\"d-sm-flex justify-content-center justify-content-sm-between\">\n");
      out.write("            <span class=\"text-muted text-center text-sm-left d-block d-sm-inline-block\">Premium <a href=\"https://www.bootstrapdash.com/\" target=\"_blank\">Bootstrap admin template</a> from BootstrapDash.</span>\n");
      out.write("            <span class=\"float-none float-sm-right d-block mt-1 mt-sm-0 text-center\">Copyright © 2021. All rights reserved.</span>\n");
      out.write("          </div>\n");
      out.write("        </footer>\n");
      out.write("        <!-- partial -->\n");
      out.write("      </div>\n");
      out.write("      <!-- main-panel ends -->\n");
      out.write("    </div>\n");
      out.write("    <!-- page-body-wrapper ends -->\n");
      out.write("  </div>\n");
      out.write("  \n");
      out.write("  \n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /star-admin2-free-admin-template/template/pages/tables/basic-table.jsp(496,26) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/star-admin2-free-admin-template/template/pages/tables/basic-table.jsp(496,26) '${Daos.findAll()}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${Daos.findAll()}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /star-admin2-free-admin-template/template/pages/tables/basic-table.jsp(496,26) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("listS");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("                              <tr>\n");
            out.write("                                <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${listS.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("                                <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${listS.tenloai}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("                                <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${listS.ngaytao}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("                                ");
            if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\n");
            out.write("                                ");
            if (_jspx_meth_c_005fif_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\n");
            out.write("                                \n");
            out.write("                              </tr>\n");
            out.write("                          ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /star-admin2-free-admin-template/template/pages/tables/basic-table.jsp(501,32) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.acc.isAdmin == 1}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                                    <td><a href=\"../../../../edits?id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${listS.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&type=edit\">Edit</a></td>\n");
          out.write("                                    <td><a href=\"../../../../delete?id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${listS.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&type=delete\">Delete</a></td>\n");
          out.write("                                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /star-admin2-free-admin-template/template/pages/tables/basic-table.jsp(505,32) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.acc.isAdmin == 0}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                                    <td><a href=\"../../../../edits?id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${listS.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&type=edit\">Edit</a></td>\n");
          out.write("                                    \n");
          out.write("                                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /star-admin2-free-admin-template/template/pages/tables/basic-table.jsp(540,26) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/star-admin2-free-admin-template/template/pages/tables/basic-table.jsp(540,26) '${PrDao.findAll()}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${PrDao.findAll()}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /star-admin2-free-admin-template/template/pages/tables/basic-table.jsp(540,26) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("listP");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("                              <tr>\n");
            out.write("                                <<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${listP.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("                                <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${listP.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("                                <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${listP.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("                                <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${listP.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("                                ");
            if (_jspx_meth_c_005fif_005f2(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
              return true;
            out.write("\n");
            out.write("                                ");
            if (_jspx_meth_c_005fif_005f3(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
              return true;
            out.write("\n");
            out.write("                              </tr>\n");
            out.write("                          ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
      // /star-admin2-free-admin-template/template/pages/tables/basic-table.jsp(546,32) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.acc.isAdmin == 1}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                                    <td><a href=\"../../../../editPs?id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${listP.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&type=edit\">Edit</a></td>\n");
          out.write("                                    <td>\n");
          out.write("\n");
          out.write("                                        <a href=\"../../../../deletePs?id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${listP.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&type=deletePr\">Delete</a>\n");
          out.write("                                    </td>\n");
          out.write("                                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
      // /star-admin2-free-admin-template/template/pages/tables/basic-table.jsp(553,32) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.acc.isAdmin == 0}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                                    <a href=\"../../../../editPs?id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${listP.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&type=edit\">Edit</a>\n");
          out.write("                                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f2_reused = false;
    try {
      _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f2.setParent(null);
      // /star-admin2-free-admin-template/template/pages/tables/basic-table.jsp(587,26) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setItems(new org.apache.jasper.el.JspValueExpression("/star-admin2-free-admin-template/template/pages/tables/basic-table.jsp(587,26) '${DaoUse.findAll()}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${DaoUse.findAll()}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /star-admin2-free-admin-template/template/pages/tables/basic-table.jsp(587,26) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setVar("listAc");
      int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
        if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("                              <tr>\n");
            out.write("                                  <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${listAc.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("                                  <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${listAc.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("                                  <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${listAc.password}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("                                  <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${listAc.sell_ID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("                                  <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${listAc.isAdmin}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("                                  ");
            if (_jspx_meth_c_005fif_005f4(_jspx_th_c_005fforEach_005f2, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f2))
              return true;
            out.write("\n");
            out.write("                                ");
            if (_jspx_meth_c_005fif_005f5(_jspx_th_c_005fforEach_005f2, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f2))
              return true;
            out.write("\n");
            out.write("                              </tr>\n");
            out.write("                          ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
      _jspx_th_c_005fforEach_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f2, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f2)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f2);
      // /star-admin2-free-admin-template/template/pages/tables/basic-table.jsp(594,34) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.acc.isAdmin == 1}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                                    <td><a href=\"../../../../accountAdmin?id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${listAc.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&type=edit\">Edit</a></td>\n");
          out.write("                                    <td>\n");
          out.write("\n");
          out.write("                                        <a href=\"../../../../accountAdmin?id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${listAc.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&type=deletePr\">Delete</a>\n");
          out.write("                                    </td>\n");
          out.write("                                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f2, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f2)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f5 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f5_reused = false;
    try {
      _jspx_th_c_005fif_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f2);
      // /star-admin2-free-admin-template/template/pages/tables/basic-table.jsp(601,32) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.acc.isAdmin == 0}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f5 = _jspx_th_c_005fif_005f5.doStartTag();
      if (_jspx_eval_c_005fif_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                                    <a href=\"../../../../accountAdmin?id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${listAc.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&type=edit\">Edit</a>\n");
          out.write("                                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f5.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
      _jspx_th_c_005fif_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /star-admin2-free-admin-template/template/pages/tables/basic-table.jsp(634,30) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("soluong");
      // /star-admin2-free-admin-template/template/pages/tables/basic-table.jsp(634,30) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/star-admin2-free-admin-template/template/pages/tables/basic-table.jsp(634,30) '${Totalmoney1.TotalMoney()}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${Totalmoney1.TotalMoney()}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f3 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f3_reused = false;
    try {
      _jspx_th_c_005fforEach_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f3.setParent(null);
      // /star-admin2-free-admin-template/template/pages/tables/basic-table.jsp(643,30) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f3.setItems(new org.apache.jasper.el.JspValueExpression("/star-admin2-free-admin-template/template/pages/tables/basic-table.jsp(643,30) '${Totalmoney1.productMax()}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${Totalmoney1.productMax()}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /star-admin2-free-admin-template/template/pages/tables/basic-table.jsp(643,30) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f3.setVar("listPM");
      int[] _jspx_push_body_count_c_005fforEach_005f3 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f3 = _jspx_th_c_005fforEach_005f3.doStartTag();
        if (_jspx_eval_c_005fforEach_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("                                  <tr>\n");
            out.write("                                      <td>\n");
            out.write("                                          \n");
            out.write("                                          <a href=\"detail?id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${listPM.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\n");
            out.write("                            <img class=\"img-fluid\" src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${listPM.image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" alt=\"alt\"/>\n");
            out.write("                        </a>\n");
            out.write("                        <a href=\"detail?id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${listPM.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"><h6 class=\"text-truncate mb-3\">Tên sản phẩm: ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${listPM.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h6></a>\n");
            out.write("                        \n");
            out.write("                                      </td>\n");
            out.write("                                  \n");
            out.write("                                 \n");
            out.write("                              </tr>\n");
            out.write("                                  ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f3.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f3[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f3.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f3.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f3);
      _jspx_th_c_005fforEach_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f4 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f4_reused = false;
    try {
      _jspx_th_c_005fforEach_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f4.setParent(null);
      // /star-admin2-free-admin-template/template/pages/tables/basic-table.jsp(658,30) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f4.setItems(new org.apache.jasper.el.JspValueExpression("/star-admin2-free-admin-template/template/pages/tables/basic-table.jsp(658,30) '${Totalmoney1.TotalAccount()}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${Totalmoney1.TotalAccount()}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /star-admin2-free-admin-template/template/pages/tables/basic-table.jsp(658,30) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f4.setVar("listAccL");
      int[] _jspx_push_body_count_c_005fforEach_005f4 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f4 = _jspx_th_c_005fforEach_005f4.doStartTag();
        if (_jspx_eval_c_005fforEach_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("                                  <tr>\n");
            out.write("                                      <td>\n");
            out.write("                                          \n");
            out.write("                        <a href=\"detail?id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${listPM.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"><h6 class=\"text-truncate mb-3\">Username: ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${listAccL.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h6></a>\n");
            out.write("                        \n");
            out.write("                                      </td>\n");
            out.write("                                  \n");
            out.write("                                 \n");
            out.write("                              </tr>\n");
            out.write("                                  ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f4.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f4[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f4.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f4.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f4);
      _jspx_th_c_005fforEach_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f4_reused);
    }
    return false;
  }
}
