/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.100
 * Generated at: 2024-06-07 02:12:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class dangky_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\" integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\" crossorigin=\"anonymous\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.3.1/css/all.css\" integrity=\"sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU\" crossorigin=\"anonymous\">\n");
      out.write("    <title>Bootstrap 4 Login/Register Form</title>\n");
      out.write("    \n");
      out.write("    <style>\n");
      out.write("    .background-radial-gradient {\n");
      out.write("      background-color: hsl(218, 41%, 15%);\n");
      out.write("      background-image: radial-gradient(650px circle at 0% 0%,\n");
      out.write("          hsl(218, 41%, 35%) 15%,\n");
      out.write("          hsl(218, 41%, 30%) 35%,\n");
      out.write("          hsl(218, 41%, 20%) 75%,\n");
      out.write("          hsl(218, 41%, 19%) 80%,\n");
      out.write("          transparent 100%),\n");
      out.write("        radial-gradient(1250px circle at 100% 100%,\n");
      out.write("          hsl(218, 41%, 45%) 15%,\n");
      out.write("          hsl(218, 41%, 30%) 35%,\n");
      out.write("          hsl(218, 41%, 20%) 75%,\n");
      out.write("          hsl(218, 41%, 19%) 80%,\n");
      out.write("          transparent 100%);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #radius-shape-1 {\n");
      out.write("      height: 220px;\n");
      out.write("      width: 220px;\n");
      out.write("      top: -60px;\n");
      out.write("      left: -130px;\n");
      out.write("      background: radial-gradient(#44006b, #ad1fff);\n");
      out.write("      overflow: hidden;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #radius-shape-2 {\n");
      out.write("      border-radius: 38% 62% 63% 37% / 70% 33% 67% 30%;\n");
      out.write("      bottom: -60px;\n");
      out.write("      right: -110px;\n");
      out.write("      width: 300px;\n");
      out.write("      height: 300px;\n");
      out.write("      background: radial-gradient(#44006b, #ad1fff);\n");
      out.write("      overflow: hidden;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .bg-glass {\n");
      out.write("      background-color: hsla(0, 0%, 100%, 0.9) !important;\n");
      out.write("      backdrop-filter: saturate(200%) blur(25px);\n");
      out.write("    }\n");
      out.write("  </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <section class=\"background-radial-gradient overflow-hidden\">\n");
      out.write("  \n");
      out.write("\n");
      out.write("  <div class=\"container px-4 py-5 px-md-5 text-center text-lg-start my-5\">\n");
      out.write("    <div class=\"row gx-lg-5 align-items-center mb-5\">\n");
      out.write("      <div class=\"col-lg-6 mb-5 mb-lg-0\" style=\"z-index: 10\">\n");
      out.write("        <h1 class=\"my-5 display-5 fw-bold ls-tight\" style=\"color: hsl(218, 81%, 95%)\">\n");
      out.write("          The best offer <br />\n");
      out.write("          <span style=\"color: hsl(218, 81%, 75%)\">for your business</span>\n");
      out.write("        </h1>\n");
      out.write("        <p class=\"mb-4 opacity-70\" style=\"color: hsl(218, 81%, 85%)\">\n");
      out.write("          Lorem ipsum dolor, sit amet consectetur adipisicing elit.\n");
      out.write("          Temporibus, expedita iusto veniam atque, magni tempora mollitia\n");
      out.write("          dolorum consequatur nulla, neque debitis eos reprehenderit quasi\n");
      out.write("          ab ipsum nisi dolorem modi. Quos?\n");
      out.write("        </p>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <div class=\"col-lg-6 mb-5 mb-lg-0 position-relative\">\n");
      out.write("        <div id=\"radius-shape-1\" class=\"position-absolute rounded-circle shadow-5-strong\"></div>\n");
      out.write("        <div id=\"radius-shape-2\" class=\"position-absolute shadow-5-strong\"></div>\n");
      out.write("\n");
      out.write("        <div class=\"card bg-glass\">\n");
      out.write("          <div class=\"card-body px-4 py-5 px-md-5\">\n");
      out.write("              <form action=\"dangky\" method=\"post\">\n");
      out.write("                  <p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mess}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\n");
      out.write("              <!-- 2 column grid layout with text inputs for the first and last names -->\n");
      out.write("              <div class=\"row\">\n");
      out.write("                <div class=\"col-md-6 mb-4\">\n");
      out.write("                  <div class=\"form-outline\">\n");
      out.write("                      <input type=\"text\" name=\"user\" id=\"form3Example2\" class=\"form-control\" />\n");
      out.write("                    <label class=\"form-label\" for=\"form3Example2\">Last name</label>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("\n");
      out.write("              <!-- Email input -->\n");
      out.write("              <div class=\"form-outline mb-4\">\n");
      out.write("                  <input type=\"password\" name=\"pass\" id=\"form3Example3\" class=\"form-control\" />\n");
      out.write("                <label class=\"form-label\" for=\"form3Example3\">Email address</label>\n");
      out.write("              </div>\n");
      out.write("\n");
      out.write("              <!-- Password input -->\n");
      out.write("              <div class=\"form-outline mb-4\">\n");
      out.write("                  <input type=\"password\" name=\"repass\" id=\"form3Example4\" class=\"form-control\" />\n");
      out.write("                <label class=\"form-label\" for=\"form3Example4\">Password</label>\n");
      out.write("              </div>\n");
      out.write("\n");
      out.write("              <!-- Checkbox -->\n");
      out.write("              <div class=\"form-check d-flex justify-content-center mb-4\">\n");
      out.write("                <input class=\"form-check-input me-2\" type=\"checkbox\" value=\"\" id=\"form2Example33\" checked />\n");
      out.write("                <label class=\"form-check-label\" for=\"form2Example33\">\n");
      out.write("                  Subscribe to our newsletter\n");
      out.write("                </label>\n");
      out.write("              </div>\n");
      out.write("\n");
      out.write("              <!-- Submit button -->\n");
      out.write("              <button type=\"submit\" class=\"btn btn-primary btn-block mb-4\">\n");
      out.write("                Sign up\n");
      out.write("              </button>\n");
      out.write("\n");
      out.write("              <!-- Register buttons -->\n");
      out.write("              <div class=\"text-center\">\n");
      out.write("                <p>or sign up with:</p>\n");
      out.write("                <button type=\"button\" class=\"btn btn-link btn-floating mx-1\">\n");
      out.write("                  <i class=\"fab fa-facebook-f\"></i>\n");
      out.write("                </button>\n");
      out.write("\n");
      out.write("                <button type=\"button\" class=\"btn btn-link btn-floating mx-1\">\n");
      out.write("                  <i class=\"fab fa-google\"></i>\n");
      out.write("                </button>\n");
      out.write("\n");
      out.write("                <button type=\"button\" class=\"btn btn-link btn-floating mx-1\">\n");
      out.write("                  <i class=\"fab fa-twitter\"></i>\n");
      out.write("                </button>\n");
      out.write("\n");
      out.write("                <button type=\"button\" class=\"btn btn-link btn-floating mx-1\">\n");
      out.write("                  <i class=\"fab fa-github\"></i>\n");
      out.write("                </button>\n");
      out.write("              </div>\n");
      out.write("            </form>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</section>\n");
      out.write("    \n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
