/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.100
 * Generated at: 2024-06-07 02:01:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class dangnhap_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\" integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\" crossorigin=\"anonymous\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.3.1/css/all.css\" integrity=\"sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU\" crossorigin=\"anonymous\">\n");
      out.write("    <title>Bootstrap 4 Login/Register Form</title>\n");
      out.write("    \n");
      out.write("    <style>\n");
      out.write("        \n");
      out.write(".gradient-custom-2 {\n");
      out.write("/* fallback for old browsers */\n");
      out.write("background: #fccb90;\n");
      out.write("\n");
      out.write("/* Chrome 10-25, Safari 5.1-6 */\n");
      out.write("background: -webkit-linear-gradient(to right, #ee7724, #d8363a, #dd3675, #b44593);\n");
      out.write("\n");
      out.write("/* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */\n");
      out.write("background: linear-gradient(to right, #ee7724, #d8363a, #dd3675, #b44593);\n");
      out.write("}\n");
      out.write("\n");
      out.write("@media (min-width: 768px) {\n");
      out.write(".gradient-form {\n");
      out.write("height: 100vh !important;\n");
      out.write("}\n");
      out.write("}\n");
      out.write("@media (min-width: 769px) {\n");
      out.write(".gradient-custom-2 {\n");
      out.write("border-top-right-radius: .3rem;\n");
      out.write("border-bottom-right-radius: .3rem;\n");
      out.write("}\n");
      out.write("}\n");
      out.write("\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <section class=\"h-100 gradient-form\" style=\"background-color: #eee;\">\n");
      out.write("  <div class=\"container py-5 h-100\">\n");
      out.write("    <div class=\"row d-flex justify-content-center align-items-center h-100\">\n");
      out.write("      <div class=\"col-xl-10\">\n");
      out.write("        <div class=\"card rounded-3 text-black\">\n");
      out.write("          <div class=\"row g-0\">\n");
      out.write("            <div class=\"col-lg-6\">\n");
      out.write("              <div class=\"card-body p-md-5 mx-md-4\">\n");
      out.write("\n");
      out.write("                <div class=\"text-center\">\n");
      out.write("                    <img src=\"img/Logo-ngang-01.png\"\n");
      out.write("                    style=\"width: 185px;\" alt=\"logo\">\n");
      out.write("                  <h4 class=\"mt-1 mb-5 pb-1\">We are Tra Sua Team</h4>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                  <form action=\"login\" method=\"post\">\n");
      out.write("                      <p>Please login to your account</p>\n");
      out.write("\n");
      out.write("                  <div class=\"form-outline mb-4\">\n");
      out.write("                      <input type=\"text\" name=\"user\" id=\"user\" class=\"form-control\"\n");
      out.write("                      placeholder=\"Phone number or email address\" />\n");
      out.write("                    <label class=\"form-label\" for=\"form2Example11\">Username</label>\n");
      out.write("                  </div>\n");
      out.write("\n");
      out.write("                  <div class=\"form-outline mb-4\">\n");
      out.write("                      <input type=\"password\" name=\"pass\" id=\"pass\" class=\"form-control\" />\n");
      out.write("                    <label class=\"form-label\" for=\"form2Example22\">Password</label>\n");
      out.write("                  </div>\n");
      out.write("\n");
      out.write("                  <div class=\"text-center pt-1 mb-5 pb-1\">\n");
      out.write("                    <button class=\"btn btn-primary btn-block fa-lg gradient-custom-2 mb-3\" type=\"submit\">Log\n");
      out.write("                      in</button>\n");
      out.write("                    <a class=\"text-muted\" href=\"#!\">Forgot password?</a>\n");
      out.write("                  </div>\n");
      out.write("\n");
      out.write("                  <div class=\"d-flex align-items-center justify-content-center pb-4\">\n");
      out.write("                    <p class=\"mb-0 me-2\">Don't have an account?</p>\n");
      out.write("                    <button type=\"button\" class=\"btn btn-outline-danger\">Create new</button>\n");
      out.write("                  </div>\n");
      out.write("                  </form>\n");
      out.write("\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-lg-6 d-flex align-items-center gradient-custom-2\">\n");
      out.write("              <div class=\"text-white px-3 py-4 p-md-5 mx-md-4\">\n");
      out.write("                  <a href=\"dangky.jsp\"><h4 class=\"mb-4\">Đăng ký</h4></a>\n");
      out.write("                <p class=\"small mb-0\">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n");
      out.write("                  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud\n");
      out.write("                  exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</section>\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
